language: "en"

version: "3.1"

pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "LexicalSyntacticFeaturizer"
- name: "CountVectorsFeaturizer"
- name: "CountVectorsFeaturizer"
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: "DIETClassifier"
  epochs: 100
  constrain_similarities: true
- name: "FallbackClassifier"
  threshold: 0.7
  ambiguity_threshold: 0.1
  fallback_intent_name: "out_of_scope"

policies:
- name: "MemoizationPolicy"
  max_history: 5
- name: "RulePolicy"
  core_fallback_action_name: "action_llama_fallback"
  core_fallback_threshold: 0.3
  enable_fallback_prediction: true
- name: "TEDPolicy"
  max_history: 5
  epochs: 50

assistant_id: 20250421-140934-drab-pascal
